version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: intelliplan-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: intelliplan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - intelliplan-postgres-data:/var/lib/postgresql/data

volumes:
  intelliplan-postgres-data:
